### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by leonichel** [siavash-khodadadeh/Meta-Learning-Framework#1]
Hi, congratulation for your work. It's super nice. Please, can you write a documentation?

**Comment by siavash-khodadadeh** [comment]
Hello, thank you! Please look at our newer repository for meta-learning with TF2.0: [https://github.com/siavash-khodadadeh/MetaLearning-TF2.0](https://github.com/siavash-khodadadeh/MetaLearning-TF2.0)

**Comment by leonichel** [comment]
Amazing. I liked so much. Thanks! Sorry for my mistake. :D

**Comment by siavash-khodadadeh** [comment]
Happy to hear that. No worries at all.
